HOME_ICON="home"
PROJECT_LIST_ICON="database"
PROJECT_ICON="archive"
DATA_LIST_ICON="file text"
DATA_ICON="file"
ANALYSIS_LIST_ICON="settings"
ANALYSIS_ICON="setting"
RESULT_LIST_ICON="bar chart"
RESULT_ICON="bar chart"

