# Generated by Django 2.0.6 on 2018-06-26 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'New'), (1, 'Active'), (2, 'Suspended'), (3, 'Banned')], default=0)),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(default='', max_length=80)),
                ('max_upload_size', models.IntegerField(default=0)),
                ('role', models.IntegerField(choices=[(0, 'User'), (1, 'Moderator'), (2, 'Manager'), (3, 'Blog User')], default=0)),
                ('last_login', models.DateTimeField(null=True)),
                ('new_messages', models.IntegerField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.URLField(blank=True, default='', max_length=255)),
                ('scholar', models.CharField(blank=True, default='', max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('twitter', models.CharField(blank=True, default='', max_length=255)),
                ('my_tags', models.TextField(blank=True, default='', max_length=255)),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('html', models.TextField(blank=True, default='', null=True)),
                ('notify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
