# Generated by Django 2.2 on 2019-04-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190403_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='message_prefs',
            field=models.IntegerField(choices=[(0, 'Local messages'), (1, 'Email for every new post added to current one.'), (2, 'Email for every new thread (mailing list mode)')], default=0),
        ),
    ]
