# Generated by Django 2.2 on 2019-05-23 13:56

import biostar.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mailing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=1024, null=True, upload_to=biostar.accounts.models.image_path),
        ),
    ]
