# Generated by Django 2.2 on 2019-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_message_prefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='message_prefs',
            field=models.IntegerField(choices=[(2, 'no messages'), (3, 'default'), (0, 'local messages'), (1, 'email'), (4, 'email for every new thread (mailing list mode)')], default=3),
        ),
    ]
