# Generated by Django 2.2 on 2019-06-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Reader'), (1, 'Moderator'), (2, 'Admin'), (3, 'Blog User')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=models.TextField(blank=True, default='No profile information', max_length=10000, null=True),
        ),
    ]
