# Generated by Django 2.2 on 2019-08-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_spamrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_digest',
            field=models.DateTimeField(db_index=True, max_length=255, null=True),
        ),
    ]
