# Generated by Django 2.2 on 2019-08-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_spamrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='digest_prefs',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Email for every new thread (mailing list mode)')], default=0),
        ),
    ]
