# Generated by Django 2.2 on 2019-09-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_last_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Active'), (4, 'Inactive'), (2, 'Suspended'), (3, 'Banned')], db_index=True, default=0),
        ),
    ]
