# Generated by Django 2.2.7 on 2020-01-23 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_watched_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Reader'), (1, 'Moderator'), (2, 'Admin'), (3, 'Blog User')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Active'), (4, 'Spammer'), (2, 'Suspended'), (3, 'Banned')], db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(0, 'Preformed a moderation action.'), (1, 'Created an object.'), (2, 'Edited an object.'), (3, 'Logged in to the site.'), (4, 'Logged out of the site.'), (5, 'Browsing the site.')], default=5)),
                ('log_text', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
