# Generated by Django 3.1 on 2020-09-17 22:53

from django.db import migrations, models
import uuid


def get_uuid(limit=32):
    return str(uuid.uuid4())[:limit]


def add_token(apps, schema_editor):

    Profile = apps.get_model('accounts', 'Profile')
    profiles = Profile.objects.all()
    for pro in profiles:
        # Set a token for this user.
        pro.token = get_uuid(32)
        pro.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    migrations.RunPython(add_token),
    ]
