# Generated by Django 3.1 on 2020-10-24 20:38
import os
from django.db import migrations, models

from django.conf import settings


def join(*args):
    return os.path.abspath(os.path.join(*args))


def update_default(apps, schema_editor):

    Profile = apps.get_model('accounts', 'Profile')
    NO_DIGEST, DAILY_DIGEST, WEEKLY_DIGEST, MONTHLY_DIGEST, ALL_MESSAGES = range(5)

    profiles = Profile.objects.all()
    for prf in profiles:
        # Update previous 'weekly digest' default to no digest.
        if prf.digest_prefs == WEEKLY_DIGEST:
            prf.digest_prefs = NO_DIGEST
            prf.save()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='digest_prefs',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Email for every new thread (mailing list mode)')], default=0),
        ),
        migrations.RunPython(update_default),
    ]
