# Generated by Django 3.1 on 2020-10-01 17:08

from django.db import migrations, models

import uuid


def get_uuid(limit=32):
    return str(uuid.uuid4())[:limit]


def add_token(apps, schema_editor):

    Profile = apps.get_model('accounts', 'Profile')
    profiles = Profile.objects.all()
    for pro in profiles:
        # Set a token for users.
        pro.token = get_uuid(16)
        pro.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_digest_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(add_token),
    ]
