# Generated by Django 3.1.6 on 2021-02-10 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.IntegerField(choices=[(0, 'Moderate'), (1, 'Create'), (2, 'Edit'), (3, 'Login'), (4, 'Logout'), (5, 'Default')], db_index=True, default=5)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Logger',
        ),
    ]
