# Generated by Django 3.1 on 2021-02-20 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_logger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='uid',
        ),
    ]
