# Generated by Django 3.1 on 2021-03-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_gravatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
