# Generated by Django 3.1 on 2021-03-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_watched_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='handle',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
