import os
# Datatypes



RADIO = "RADIO"
DROPDOWN = "DROPDOWN"
INTEGER = "INTEGER"
FLOAT = "FLOAT"
UPLOAD = "UPLOAD"
MODEL = "MODEL"
SCRIPT = "SCRIPT"
CHECKBOX = "CHECKBOX"
TEMPLATE = "TEMPLATE"




GENERIC_TYPE = 0
SAMPLE_TYPE = 1
COLLECTION_TYPE = 2
TAR_FASTQ_GZ = 3
FASTQ_TYPE = 4
FASTA_TYPE = 5

DATA_TYPES = dict(
    GENERIC_TYPE=GENERIC_TYPE, SAMPLE_TYPE=SAMPLE_TYPE, COLLECTION_TYPE=SAMPLE_TYPE,
    TAR_FASTQ_GZ=TAR_FASTQ_GZ, FASTQ_TYPE=FASTQ_TYPE, FASTA_TYPE=FASTA_TYPE
)


SEQUENCE_TYPES =[FASTA_TYPE, FASTQ_TYPE]

TAR_GZ = "TAR_GZ"

LAMAR_SAMPLE_SHEET = "LAMAR"

FIELD_ORIGIN = "origin"
PROJECT_ORIGIN = "PROJECT"
