import os
# Datatypes



RADIO = "RADIO"
DROPDOWN = "DROPDOWN"
INTEGER = "INTEGER"
FLOAT = "FLOAT"
UPLOAD = "UPLOAD"
MODEL = "MODEL"
SCRIPT = "SCRIPT"
CHECKBOX = "CHECKBOX"
TEMPLATE = "TEMPLATE"

FASTQ_TYPE = "FASTQ"
FASTA_TYPE = "FASTA"

SEQUENCE_TYPES =[FASTA_TYPE, FASTQ_TYPE]

TAR_GZ = "TAR_GZ"

LAMAR_SAMPLE_SHEET = "LAMAR"

FIELD_ORIGIN = "origin"
PROJECT_ORIGIN = "PROJECT"
