# Generated by Django 2.0.8 on 2018-09-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='security',
            field=models.IntegerField(choices=[(1, 'Runnable'), (2, 'Not Runnable')], default=2),
        ),
    ]
