# Generated by Django 2.0.8 on 2018-09-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20180924_2050'),
        ('engine', '0002_bigint'),
    ]

    operations = [
    ]
