# Generated by Django 2.1.2 on 2018-10-28 18:46

from django.db import migrations, models
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


def format_summary(apps, schema_editor):
    """
    Add the summary as first line of text.
    """

    def formatter(model_name):
        queryset = apps.get_model('engine', model_name=model_name)
        for obj in queryset.objects.all():
            obj.text = obj.summary + "\n" + obj.text
            obj.save()

    for name in ["Analysis", "Data", "Job", "Project"]:
        formatter(model_name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_bigint'),
    ]

    operations = [
        migrations.RunPython(format_summary),

        migrations.RemoveField(
            model_name='analysis',
            name='summary',
        ),

        migrations.RemoveField(
            model_name='data',
            name='summary',
        ),

        migrations.RemoveField(
            model_name='job',
            name='summary',
        ),

        migrations.RemoveField(
            model_name='project',
            name='summary',
        ),
        migrations.AlterField(
            model_name='access',
            name='access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'Read Access'), (3, 'Write Access')], db_index=True, default=1),
        ),

        migrations.AddField(
            model_name='analysis',
            name='lastedit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),

        migrations.AddField(
            model_name='analysis',
            name='lastedit_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='analysis_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='data',
            name='lastedit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='data',
            name='lastedit_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_editor',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='lastedit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='lastedit_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_editor',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='lastedit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='lastedit_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_editor',
                                    to=settings.AUTH_USER_MODEL),
        ),

    ]
