# Generated by Django 2.1.5 on 2019-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_lastedit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='sticky',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sticky',
        ),
        migrations.RemoveField(
            model_name='job',
            name='sticky',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sticky',
        ),
        migrations.AddField(
            model_name='analysis',
            name='rank',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='data',
            name='rank',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.FloatField(default=100),
        ),
    ]
