# Generated by Django 2.2.1 on 2019-05-21 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Local messages.'), (1, 'Email messages.'), (2, 'Mailing list.')], db_index=True, default=0)),
                ('source', models.IntegerField(choices=[(0, 'From project discussion'), (1, 'Mentioned in a post'), (2, 'Regular')], db_index=True, default=2)),
                ('spam', models.IntegerField(choices=[(0, 'Spam'), (1, 'Not spam'), (2, 'Unknown')], default=2)),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('subject', models.CharField(max_length=120)),
                ('sender_deleted', models.BooleanField(default=False)),
                ('recipient_deleted', models.BooleanField(default=False)),
                ('body', models.TextField(max_length=10000)),
                ('html', models.TextField(default='', max_length=100000)),
                ('unread', models.BooleanField(default=True)),
                ('sent_date', models.DateTimeField(db_index=True, null=True)),
                ('parent_msg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_messages', to='message.Message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='', max_length=10000)),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('blocked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked', to=settings.AUTH_USER_MODEL)),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
