# Generated by Django 2.0.8 on 2018-09-09 20:52

import biostar.forum.models
from django.conf import settings
import django.contrib.auth
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rank', models.FloatField(blank=True, default=0)),
                ('has_accepted', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Open'), (2, 'Closed'), (3, 'Deleted')], default=1)),
                ('type', models.IntegerField(choices=[(0, 'Question'), (1, 'Answer'), (6, 'Comment'), (2, 'Job'), (3, 'Forum'), (8, 'Tutorial'), (7, 'Data'), (4, 'Page'), (10, 'Tool'), (11, 'News'), (5, 'Blog'), (9, 'Bulletin Board')], db_index=True)),
                ('vote_count', models.IntegerField(blank=True, db_index=True, default=0)),
                ('view_count', models.IntegerField(blank=True, db_index=True, default=0)),
                ('reply_count', models.IntegerField(blank=True, db_index=True, default=0)),
                ('comment_count', models.IntegerField(blank=True, default=0)),
                ('book_count', models.IntegerField(default=0)),
                ('subs_count', models.IntegerField(default=0)),
                ('thread_votecount', models.IntegerField(default=0)),
                ('thread_score', models.IntegerField(blank=True, db_index=True, default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lastedit_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sticky', models.BooleanField(default=False)),
                ('content', models.TextField(default='')),
                ('html', models.TextField(default='')),
                ('tag_val', models.CharField(blank=True, default='', max_length=100)),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('author', models.ForeignKey(on_delete=models.SET(biostar.forum.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('lastedit_user', models.ForeignKey(null=True, on_delete=models.SET(biostar.forum.models.get_sentinel_user), related_name='editor', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='forum.Post')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Project')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendants', to='forum.Post')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('thread_users', models.ManyToManyField(related_name='thread_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, default='', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='forum.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'Not following'), (1, 'Follow using Local Messages'), (2, 'Follow using Emails')], default=1)),
                ('date', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='forum.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Upvote'), (4, 'Empty'), (1, 'DownVote'), (2, 'Bookmark'), (3, 'Accept')], db_index=True, default=4)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('author', models.ForeignKey(on_delete=models.SET(django.contrib.auth.get_user_model), to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.Post')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'post')},
        ),
    ]
