# Generated by Django 2.2 on 2019-06-11 12:58

from django.db import migrations, models

def add_toplevel(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Post = apps.get_model('forum', 'Post')
    Post.objects.filter(type__in=(0,2,3,4,5,7,8,9,10,11,12)).update(is_toplevel=True)


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_toplevel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.IntegerField(choices=[(3, 'Default'), (1, 'Email'), (0, 'Local Messages'), (2, 'No messages')], default=0),
        ),
        migrations.RunPython(add_toplevel),
    ]
