# Generated by Django 2.2 on 2019-05-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.IntegerField(choices=[(0, 'Local messages.'), (1, 'Email messages.'), (2, 'Mailing list.')], default=0),
        ),
    ]
