# Generated by Django 2.2 on 2019-04-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='spam',
            field=models.IntegerField(choices=[(0, 'Spam'), (1, 'On topic'), (2, 'Useful')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='has_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='lastedit_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='rank',
            field=models.FloatField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Open'), (2, 'Closed'), (3, 'Deleted')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='thread_votecount',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='uid',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.IntegerField(choices=[(3, 'default'), (0, 'local messages'), (1, 'email'), (4, 'email for every new thread (mailing list mode)')], default=0),
        ),
    ]
