# Generated by Django 2.2 on 2019-06-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_add_toplevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_toplevel',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.IntegerField(choices=[(0, 'Local messages'), (1, 'Email message'), (2, 'Not subscribed')], default=0, null=True),
        ),
    ]
