# Generated by Django 2.1.2 on 2018-10-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='has_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
