# Generated by Django 2.2 on 2019-04-10 12:15

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('forum', '0003_auto_20190407_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='spam',
            field=models.IntegerField(choices=[(0, 'Spam'), (1, 'Non spam'), (2, 'New post')], default=2),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.IntegerField(choices=[(3, 'default'), (0, 'local messages'), (1, 'email'), (4, 'email for every new thread (mailing list mode)')], default=0),
        ),
    ]
