# Generated by Django 2.2 on 2019-04-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_award_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.IntegerField(choices=[(3, 'Default to Local Messages'), (0, 'Local messages'), (1, 'Email for every new post added to current one.'), (4, 'Email for every new thread (mailing list mode)')], default=0),
        ),
    ]
