# Generated by Django 2.2 on 2019-04-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_sub_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='context',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='count',
        ),
    ]
