# Generated by Django 2.2 on 2019-05-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_count_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='spam',
            field=models.IntegerField(choices=[(0, 'Spam'), (1, 'Not spam'), (2, 'Unknown')], default=2),
        ),
    ]
