# Generated by Django 3.1 on 2020-10-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
