# Generated by Django 3.1 on 2021-02-11 16:24

from django.db import migrations, models


def change_quar(apps, schema_editor):
    """
    Change previously quarantined posts to DEFAULT
    """
    Post = apps.get_model('forum', 'Post')
    SUSPECT = 3
    posts = Post.objects.filter(spam=SUSPECT)

    # Change spam state
    for post in posts:
        post.spam = Post.DEFAULT
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_vote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='spam',
            field=models.IntegerField(choices=[(0, 'Spam'), (1, 'Not spam'), (2, 'Default')], db_index=True, default=2),
        ),
        migrations.RunPython(change_quar),
    ]
