# Generated by Django 3.1 on 2021-02-13 21:36

from django.db import migrations
from django.template.defaultfilters import slugify


def badge_uids(apps, schema_editor):
    """
    Change badge uids to it's name
    """
    Badge = apps.get_model('forum', 'Badge')

    badges = Badge.objects.all()

    for badge in badges:

        badge.uid = slugify(badge.name)

        badge.save()


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_spam_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sync',
        ),
    migrations.RunPython(badge_uids),
    ]
