# Generated by Django 3.1 on 2021-03-19 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0013_remove_uids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.IntegerField(choices=[(0, 'Moderate'), (1, 'Create'), (2, 'Edit'), (3, 'Login'), (4, 'Logout'), (5, 'Classify'), (6, 'Default')], db_index=True, default=6)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
