# Generated by Django 3.2 on 2021-04-26 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0017_expanded_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=10000)),
                ('text', models.TextField(max_length=10000)),
                ('html', models.TextField(max_length=10000)),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'New link'), (1, 'Rejected'), (2, 'Published')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
