# Generated by Django 3.2 on 2021-05-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_shared_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='status',
            field=models.IntegerField(choices=[(0, 'Submitted'), (1, 'Rejected'), (3, 'Published'), (2, 'Accepted')], db_index=True, default=0),
        ),
    ]
