# Generated by Django 3.2 on 2021-05-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_sharedlink_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedlink',
            name='status',
            field=models.IntegerField(choices=[(0, 'Submitted'), (1, 'Declined'), (3, 'Published'), (2, 'Accepted')], db_index=True, default=0),
        ),
    ]
