# Generated by Django 3.2 on 2021-07-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_diff',
            field=models.BooleanField(default=False),
        ),
    ]
