# Generated by Django 3.2.15 on 2023-08-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_post_has_diff'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
