# Generated by Django 2.2 on 2019-05-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('state', models.IntegerField(choices=[(1, 'Active'), (2, 'Deleted'), (3, 'Inactive'), (4, 'Unsubscribed')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('text', models.CharField(max_length=10000)),
                ('html', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('state', models.IntegerField(choices=[(1, 'Active'), (2, 'Deleted'), (3, 'Inactive'), (4, 'Unsubscirbed')], default=1)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailer.EmailAddress')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailer.EmailGroup')),
            ],
        ),
    ]
