# Generated by Django 3.2 on 2021-05-24 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('state', models.IntegerField(choices=[(1, 'Active'), (2, 'Deleted'), (3, 'Unsubscribed')], default=1)),
                ('email', models.CharField(default='', max_length=256)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailer.emailgroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='address',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='group',
        ),
        migrations.DeleteModel(
            name='EmailAddress',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
