# Generated by Django 2.2 on 2019-07-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_inital'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='access',
            table='engine_access',
        ),
        migrations.AlterModelTable(
            name='analysis',
            table='engine_analysis',
        ),
        migrations.AlterModelTable(
            name='data',
            table='engine_data',
        ),
        migrations.AlterModelTable(
            name='job',
            table='engine_job',
        ),
        migrations.AlterModelTable(
            name='project',
            table='engine_project',
        ),
    ]
