# Generated by Django 2.2.6 on 2019-10-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_snippet_snippettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='name',
            field=models.CharField(default='New Recipe', max_length=256),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='security',
            field=models.IntegerField(choices=[(1, 'Trusted users may run the recipe'), (2, 'Only administrators may run the recipe')], default=2),
        ),
    ]
