# Generated by Django 2.2 on 2019-11-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_filelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileList',
        ),
        migrations.AddField(
            model_name='project',
            name='sharable_token',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='access',
            name='access',
            field=models.IntegerField(choices=[(1, 'No Access'), (2, 'Read Access'), (3, 'Write Access'), (4, 'Share Access ( Can view sharable projects ).')], db_index=True, default=1),
        ),
    ]
