# Generated by Django 3.0.2 on 2020-02-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_count',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='jobs_count',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='recipes_count',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
    ]
