# Generated by Django 3.0.3 on 2020-02-16 01:01

from django.db import migrations, models

import hjson, toml

def init_toml(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Recipes = apps.get_model('recipes', 'Analysis')

    for recipe in Recipes.objects.all():

        # Load the json data
        json_data = hjson.loads(recipe.json_text)
        toml_text = toml.dumps(json_data)

        # Bypass modifying the date on each recipe
        Recipes.objects.filter(id=recipe.id).update(json_text=toml_text)

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='phony_field',
            field=models.TextField(default='{}', max_length=10000),
        ),
        migrations.RunPython(init_toml),
    ]
