# Generated by Django 3.0.2 on 2020-02-17 22:42

from django.db import migrations, models
import hjson
import toml


def init_toml(apps, schema_editor):
    Recipes = apps.get_model('recipes', 'Analysis')
    for recipe in Recipes.objects.all():
        # Load the json data
        json_data = hjson.loads(recipe.json_text)
        toml_text = toml.dumps(json_data)
        # Bypass modifying the date on each recipe
        Recipes.objects.filter(id=recipe.id).update(json_text=toml_text)


def init_label(apps, schema_editor):
    Project = apps.get_model('recipes', 'Project')

    for project in Project.objects.all():

        # Bypass modifying the date on each project
        Project.objects.filter(id=project.id).update(label=project.uid)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='diff_author',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='diff_date',
        ),
        migrations.AddField(
            model_name='project',
            name='label',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='json_text',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.RunPython(init_toml),
        migrations.RunPython(init_label),
    ]
