# Generated by Django 3.0.2 on 2020-02-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='diff_author',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='diff_date',
        ),
        migrations.AddField(
            model_name='analysis',
            name='phony_field',
            field=models.TextField(default='{}', max_length=10000),
        ),
        migrations.AddField(
            model_name='analysis',
            name='visible_uid',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='data',
            name='visible_uid',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='visible_uid',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='visible_uid',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
