# Generated by Django 3.0.2 on 2020-02-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_analysis_phony_field'),
        ('recipes', '0008_visible_uid'),
    ]

    operations = [
    ]
