# Generated by Django 3.0.2 on 2020-03-04 01:44
import os

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_toml'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='dir',
            field=models.FilePathField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='data',
            name='toc',
            field=models.FilePathField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='project',
            name='dir',
            field=models.FilePathField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='security',
            field=models.IntegerField(choices=[(1, 'Trusted users'), (2, 'Admin only')], default=2),
        ),

    ]
