# Generated by Django 3.0.2 on 2020-06-11 17:50
import os
from django.db import migrations, models
from django.conf import settings
import toml
from django.template import loader
import mistune


def join(*args):
    return os.path.abspath(os.path.join(*args))


def correct_text(apps, schema_editor):
    Job = apps.get_model('recipes', 'Job')

    jobs = Job.objects.all()
    for job in jobs:

        # Create the parameter summary from markdown template
        summary_template = "widgets/job_summary.md"
        try:
            json_data = toml.loads(job.json_text)
        except Exception as exc:
            json_data = {}

        context = dict(data=json_data)
        # render template
        template = loader.get_template(summary_template)

        # Update the text and html
        job.text = f"Results generated by running the recipe.\n{template.render(context)}"
        job.html = mistune.markdown(job.text, escape=False)
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='text',
            field=models.TextField(default='Results generated by running the recipe.', max_length=10000),
        ),
    migrations.RunPython(correct_text),
    ]
