# Generated by Django 3.0.2 on 2020-08-08 12:29

from django.db import migrations


def order_rank(apps, schema_editor):
    """
    Gives project and recipe ranks a sequential order.
    """

    projects = apps.get_model('recipes', 'Project')
    projects = projects.objects.all()
    recipes = apps.get_model('recipes', 'Analysis')
    recipes = recipes.objects.all()

    # Update the ranks to be pk's.

    for prj in projects:
        prj.rank = prj.pk
        prj.save()

    for rec in recipes:
        rec.rank = rec.pk
        rec.save()

    return


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_job_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='label',
        ),
    migrations.RunPython(order_rank),
    ]
