# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='makefile_template',
            field=models.TextField(default='makefile'),
        ),
    ]
