# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_analysis_makefile_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='engine.Project'),
            preserve_default=False,
        ),
    ]
