# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_analysis_makefile_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='json_file',
        ),
        migrations.AddField(
            model_name='data',
            name='size',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
