# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_analysis_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='json_file',
        ),
        migrations.AddField(
            model_name='data',
            name='data_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='json_data',
            field=models.TextField(default='{}'),
        ),
    ]
