# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_data_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='path',
        ),
    ]
