# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_remove_data_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='path',
            field=models.FilePathField(null=True),
        ),
    ]
