# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_data_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='base_state',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='data',
            name='base_state',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='base_state',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='base_state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.IntegerField(choices=[(1, 'Queued'), (2, 'Running'), (3, 'Finished'), (4, 'Error')], default=1),
        ),
    ]
