# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20171016_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='base_state',
        ),
        migrations.RemoveField(
            model_name='data',
            name='base_state',
        ),
        migrations.RemoveField(
            model_name='job',
            name='base_state',
        ),
        migrations.RemoveField(
            model_name='project',
            name='base_state',
        ),
        migrations.AddField(
            model_name='analysis',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='data',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='job_state',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
