# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20171016_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='json_data',
            new_name='json_text',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='json_data',
            new_name='json_text',
        ),
    ]
