# Generated by Django 2.2.7 on 2020-01-19 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('desc', models.TextField(blank=True, default='')),
                ('feed', models.URLField()),
                ('link', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('list_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(default='', max_length=20000)),
                ('html', models.TextField(default='')),
                ('creation_date', models.DateTimeField(db_index=True)),
                ('insert_date', models.DateTimeField(db_index=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('link', models.URLField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet.Blog')),
            ],
        ),
    ]
