# Generated by Django 3.1 on 2021-03-30 01:07

from django.db import migrations, models

def init_ranks(apps, schema_editor):
    BlogPost = apps.get_model('planet', 'BlogPosts')
    for post in BlogPost.objects.all():
        post.rank = post.insert_date.timestamp()
        post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0002_blog_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='rank',
            field=models.FloatField(blank=True, db_index=True, default=0),
        ),
        migrations.RunPython(init_ranks),
    ]

